### ISSUE TITLE
Any chance to return boggle game?

### ISSUE THREAD

**Issue by Domosed-gamin** [msharov/bsd-games#9]
Subj. 

Maybe change name and add small changes in rules. I just like this game and I really sad that this game was remove. :-(

**Comment by msharov** [comment]
Once you change the name and the rules, what would be left?
Besides that, I simply don't know how to make this game any fun. Boggle is not something you want to play alone; it is mind-numbingly boring when you try. The fun comes from the company of friends you play it with, and the computer is just not up to duplicating that. Your time would be better spent making the letter dice yourself and hosting a real life party.

**Comment by Domosed-gamin** [comment]
> Besides that, I simply don't know how to make this game any fun. Boggle is not something you want to play alone; it is mind-numbingly boring when you try. 

Strange... I play alone and I have fun. Anyway, thanks for your opinion and response. 

P. S. I don't like party! I like spend my spare time alone!

**Comment by msharov** [comment]
I would also argue that this type of game doesn't fit in with the others, which are games of action; in those games you DO stuff. Go North, unlock grate, catch bird, etc. In Boggle, you just think about fitting words on a grid for ten minutes. You might try inventing a new game like "wordworm", a cute caterpillar that only eats letters that belong in a word, or something like that. Fast paced action; left, right, eat letter, get squashed by a falling dictionary :) Now that's something I'd take if you want to write it.
